#ifndef FLOOR_TILES_FILE
#define FLOOR_TILES_FILE

#define TOTAL_AREAS 6
int aFLOORS[TOTAL_AREAS] = {3, 5, 7, 7, 14, 3};

string25 aAREA_NAMES[TOTAL_AREAS] = {
	"STORMVEIL CASTLE",
	"RAYA LUCARIA ACADEMY",
	"REDMANE CASTLE",
	"VOLCANO MANOR",
	"LEYNDELL ROYAL CAPITAL",
	"THE ELDEN THRONE"
};

//Can't use aFloors[] variables to determine size in startup
int aCOLS_0[3] = {3, 7, 5};
int aCOLS_1[5] = {5, 3, 5, 6, 7};
int aCOLS_2[7] = {5, 7, 5, 7, 5, 4, 7};
int aCOLS_3[7] = {5, 7, 5, 7, 3, 3, 5};
int aCOLS_4[14] = {3, 3, 5, 5, 15, 3, 3, 3, 3, 15, 13, 3, 3, 5};
int aCOLS_5[3] = {3, 7, 3};
int* aCOLS[TOTAL_AREAS] = {
	aCOLS_0,
	aCOLS_1,
	aCOLS_2,
	aCOLS_3,
	aCOLS_4,
	aCOLS_5
};

int aROWS_0[3] = {7, 7, 7};
int aROWS_1[5] = {5, 7, 7, 5, 8};
int aROWS_2[7] = {3, 3, 5, 5, 3, 9, 5};
int aROWS_3[7] = {5, 7, 5, 5, 4, 8, 7};
int aROWS_4[14] = {4, 7, 5, 3, 4, 3, 7, 7, 7, 4, 13, 3, 3, 7};
int aROWS_5[3] = {9, 7, 9};
int* aROWS[TOTAL_AREAS] = {
	aROWS_0,
	aROWS_1,
	aROWS_2,
	aROWS_3,
	aROWS_4,
	aROWS_5
};


int aFLOOR_0_0_TILES[3*7] = {
	TILE_EMPTY, TILE_UP, TILE_EMPTY,
	TILE_SPAWN, TILE_EMPTY, TILE_SPAWN,
	TILE_EMPTY, TILE_EMPTY, TILE_EMPTY,
	TILE_EMPTY, TILE_BOSS, TILE_EMPTY,
	TILE_EMPTY, TILE_EMPTY, TILE_EMPTY,
	TILE_EMPTY, TILE_EMPTY, TILE_EMPTY,
	TILE_EMPTY, TILE_FAST_TRAVEL, TILE_EMPTY
};
int aFLOOR_0_1_TILES[7*7] = {
	TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_UP, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY,
	TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_SPAWN, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY,
	TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY,
	TILE_SPAWN, TILE_EMPTY, TILE_SPAWN, TILE_SPAWN, TILE_SPAWN, TILE_EMPTY, TILE_SPAWN,
	TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY,
	TILE_EMPTY, TILE_EMPTY, TILE_SPAWN, TILE_EMPTY, TILE_SPAWN, TILE_EMPTY, TILE_EMPTY,
	TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_DOWN, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY
};
int aFLOOR_0_2_TILES[5*7] = {
	TILE_EMPTY, TILE_EMPTY, TILE_LOCKED_FAST_TRAVEL, TILE_EMPTY, TILE_EMPTY,
	TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY,
	TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY,
	TILE_EMPTY, TILE_EMPTY, TILE_BOSS, TILE_EMPTY, TILE_EMPTY,
	TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY,
	TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY,
	TILE_EMPTY, TILE_EMPTY, TILE_DOWN, TILE_EMPTY, TILE_EMPTY
};


int aFLOOR_1_0_TILES[5*5] = {
	TILE_EMPTY, TILE_EMPTY, TILE_FAST_TRAVEL, TILE_EMPTY, TILE_EMPTY,
	TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY,
	TILE_EMPTY, TILE_INVALID, TILE_BOSS, TILE_LOCKED_FAST_TRAVEL, TILE_EMPTY,
	TILE_EMPTY, TILE_SPAWN, TILE_EMPTY, TILE_SPAWN, TILE_EMPTY,
	TILE_EMPTY, TILE_EMPTY, TILE_UP, TILE_EMPTY, TILE_EMPTY
};
int aFLOOR_1_1_TILES[3*7] = {
	TILE_EMPTY, TILE_DOWN, TILE_EMPTY,
	TILE_SPAWN, TILE_EMPTY, TILE_EMPTY,
	TILE_EMPTY, TILE_EMPTY, TILE_EMPTY,
	TILE_SPAWN, TILE_EMPTY, TILE_UP,
	TILE_EMPTY, TILE_EMPTY, TILE_EMPTY,
	TILE_SPAWN, TILE_EMPTY, TILE_EMPTY,
	TILE_EMPTY, TILE_EMPTY, TILE_EMPTY
};
int aFLOOR_1_2_TILES[5*7] = {
	TILE_INVALID, TILE_EMPTY, TILE_UP, TILE_EMPTY, TILE_INVALID,
	TILE_INVALID, TILE_EMPTY, TILE_SPAWN, TILE_EMPTY, TILE_INVALID,
	TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY,
	TILE_DOWN, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_UP,
	TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY,
	TILE_INVALID, TILE_EMPTY, TILE_SPAWN, TILE_EMPTY, TILE_INVALID,
	TILE_INVALID, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_INVALID
};
int aFLOOR_1_3_TILES[6*5] = {
	TILE_INVALID, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY,
	TILE_EMPTY, TILE_EMPTY, TILE_SPAWN, TILE_EMPTY, TILE_SPAWN, TILE_EMPTY,
	TILE_DOWN, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY,
	TILE_EMPTY, TILE_EMPTY, TILE_SPAWN, TILE_EMPTY, TILE_SPAWN, TILE_EMPTY,
	TILE_INVALID, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY
};
int aFLOOR_1_4_TILES[7*8] = {
	TILE_INVALID, TILE_INVALID, TILE_EMPTY, TILE_LOCKED_FAST_TRAVEL, TILE_EMPTY, TILE_INVALID, TILE_INVALID,
	TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY,
	TILE_EMPTY, TILE_SPAWN, TILE_EMPTY, TILE_SPAWN, TILE_EMPTY, TILE_SPAWN, TILE_EMPTY,
	TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY,
	TILE_EMPTY, TILE_SPAWN, TILE_EMPTY, TILE_BOSS, TILE_EMPTY, TILE_SPAWN, TILE_EMPTY,
	TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY,
	TILE_EMPTY, TILE_SPAWN, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_SPAWN, TILE_EMPTY,
	TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_DOWN, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY
};


int aFLOOR_2_0_TILES[5*3] = {
	TILE_INVALID, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY,
	TILE_FAST_TRAVEL, TILE_EMPTY, TILE_SPAWN, TILE_EMPTY, TILE_UP,
	TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY
};
int aFLOOR_2_1_TILES[7*3] = {
	TILE_EMPTY, TILE_SPAWN, TILE_EMPTY, TILE_SPAWN, TILE_EMPTY, TILE_SPAWN, TILE_EMPTY,
	TILE_DOWN, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_UP,
	TILE_EMPTY, TILE_SPAWN, TILE_EMPTY, TILE_SPAWN, TILE_EMPTY, TILE_SPAWN, TILE_EMPTY
};
int aFLOOR_2_2_TILES[5*5] = {
	TILE_EMPTY, TILE_EMPTY, TILE_UP, TILE_EMPTY, TILE_EMPTY,
	TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_SPAWN,
	TILE_DOWN, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY,
	TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_SPAWN,
	TILE_EMPTY, TILE_SPAWN, TILE_EMPTY, TILE_SPAWN, TILE_EMPTY
};
int aFLOOR_2_3_TILES[7*5] = {
	TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_SPAWN, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY,
	TILE_EMPTY, TILE_SPAWN, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_SPAWN, TILE_EMPTY,
	TILE_UP, TILE_SPAWN, TILE_EMPTY, TILE_SPAWN, TILE_EMPTY, TILE_SPAWN, TILE_EMPTY,
	TILE_EMPTY, TILE_SPAWN, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_SPAWN, TILE_EMPTY,
	TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_DOWN, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY
};
int aFLOOR_2_4_TILES[5*3] = {
	TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY,
	TILE_UP, TILE_EMPTY, TILE_SPAWN, TILE_EMPTY, TILE_DOWN,
	TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY
};
int aFLOOR_2_5_TILES[4*9] = {
	TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY,
	TILE_EMPTY, TILE_SPAWN, TILE_EMPTY, TILE_UP,
	TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY,
	TILE_SPAWN, TILE_EMPTY, TILE_SPAWN, TILE_INVALID,
	TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_INVALID,
	TILE_SPAWN, TILE_EMPTY, TILE_SPAWN, TILE_INVALID,
	TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY,
	TILE_EMPTY, TILE_SPAWN, TILE_EMPTY, TILE_DOWN,
	TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY
};
int aFLOOR_2_6_TILES[7*5] = {
	TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY,
	TILE_EMPTY, TILE_SPAWN, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_SPAWN, TILE_EMPTY,
	TILE_DOWN, TILE_EMPTY, TILE_EMPTY, TILE_BOSS, TILE_EMPTY, TILE_EMPTY, TILE_LOCKED_FAST_TRAVEL,
	TILE_EMPTY, TILE_SPAWN, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_SPAWN, TILE_EMPTY,
	TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY
};


int aFLOOR_3_0_TILES[5*5] = {
	TILE_EMPTY, TILE_EMPTY, TILE_UP, TILE_EMPTY, TILE_EMPTY,
	TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY,
	TILE_EMPTY, TILE_SPAWN, TILE_SPAWN, TILE_SPAWN, TILE_EMPTY,
	TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY,
	TILE_EMPTY, TILE_EMPTY, TILE_FAST_TRAVEL, TILE_EMPTY, TILE_EMPTY
};
int aFLOOR_3_1_TILES[7*7] = {
	TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_UP, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY,
	TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_SPAWN, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY,
	TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY,
	TILE_UP, TILE_SPAWN, TILE_EMPTY, TILE_SPAWN, TILE_EMPTY, TILE_SPAWN, TILE_UP,
	TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY,
	TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY,
	TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_DOWN, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY
	
};
int aFLOOR_3_2_TILES[5*5] = {
	TILE_INVALID, TILE_EMPTY, TILE_SPAWN, TILE_EMPTY, TILE_EMPTY,
	TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY,
	TILE_SPAWN, TILE_EMPTY, TILE_SPAWN, TILE_EMPTY, TILE_DOWN,
	TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY,
	TILE_INVALID, TILE_EMPTY, TILE_SPAWN, TILE_EMPTY, TILE_EMPTY
};
int aFLOOR_3_3_TILES[7*5] = {
	TILE_INVALID, TILE_EMPTY, TILE_EMPTY, TILE_UP, TILE_EMPTY, TILE_EMPTY, TILE_INVALID,
	TILE_INVALID, TILE_EMPTY, TILE_SPAWN, TILE_EMPTY, TILE_SPAWN, TILE_EMPTY, TILE_INVALID,
	TILE_DOWN, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_SPAWN,
	TILE_INVALID, TILE_EMPTY, TILE_SPAWN, TILE_EMPTY, TILE_SPAWN, TILE_EMPTY, TILE_INVALID,
	TILE_INVALID, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_INVALID
};
int aFLOOR_3_4_TILES[3*4] = {
	TILE_EMPTY, TILE_EMPTY, TILE_EMPTY,
	TILE_EMPTY, TILE_SPAWN, TILE_EMPTY,
	TILE_EMPTY, TILE_EMPTY, TILE_EMPTY,
	TILE_INVALID, TILE_DOWN, TILE_INVALID
};
int aFLOOR_3_5_TILES[3*8] = {
	TILE_EMPTY, TILE_UP, TILE_EMPTY,
	TILE_EMPTY, TILE_SPAWN, TILE_EMPTY,
	TILE_SPAWN, TILE_EMPTY, TILE_SPAWN,
	TILE_EMPTY, TILE_EMPTY, TILE_EMPTY,
	TILE_EMPTY, TILE_EMPTY, TILE_EMPTY,
	TILE_SPAWN, TILE_EMPTY, TILE_SPAWN,
	TILE_EMPTY, TILE_EMPTY, TILE_EMPTY,
	TILE_EMPTY, TILE_DOWN, TILE_EMPTY
};
int aFLOOR_3_6_TILES[5*7] = {
	TILE_EMPTY, TILE_EMPTY, TILE_LOCKED_FAST_TRAVEL, TILE_EMPTY, TILE_EMPTY,
	TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY,
	TILE_SPAWN, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_SPAWN,
	TILE_SPAWN, TILE_EMPTY, TILE_BOSS, TILE_EMPTY, TILE_SPAWN,
	TILE_SPAWN, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_SPAWN,
	TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY,
	TILE_EMPTY, TILE_EMPTY, TILE_DOWN, TILE_EMPTY, TILE_EMPTY
};


int aFLOOR_4_0_TILES[3*4] = {
	TILE_EMPTY, TILE_UP, TILE_EMPTY,
	TILE_EMPTY, TILE_EMPTY, TILE_EMPTY,
	TILE_EMPTY, TILE_EMPTY, TILE_EMPTY,
	TILE_EMPTY, TILE_FAST_TRAVEL, TILE_EMPTY
};
int aFLOOR_4_1_TILES[3*7] = {
	TILE_EMPTY, TILE_UP, TILE_EMPTY,
	TILE_SPAWN, TILE_EMPTY, TILE_SPAWN,
	TILE_EMPTY, TILE_EMPTY, TILE_EMPTY,
	TILE_SPAWN, TILE_EMPTY, TILE_SPAWN,
	TILE_EMPTY, TILE_EMPTY, TILE_EMPTY,
	TILE_SPAWN, TILE_EMPTY, TILE_SPAWN,
	TILE_EMPTY, TILE_DOWN, TILE_EMPTY
};
int aFLOOR_4_2_TILES[5*5] = {
	TILE_EMPTY, TILE_EMPTY, TILE_SPAWN, TILE_EMPTY, TILE_EMPTY,
	TILE_EMPTY, TILE_INVALID, TILE_INVALID, TILE_INVALID, TILE_EMPTY,
	TILE_SPAWN, TILE_INVALID, TILE_INVALID, TILE_INVALID, TILE_UP,
	TILE_EMPTY, TILE_INVALID, TILE_INVALID, TILE_INVALID, TILE_EMPTY,
	TILE_EMPTY, TILE_EMPTY, TILE_DOWN, TILE_EMPTY, TILE_EMPTY
};
int aFLOOR_4_3_TILES[5*3] = {
	TILE_EMPTY, TILE_EMPTY, TILE_UP, TILE_EMPTY, TILE_EMPTY,
	TILE_DOWN, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY,
	TILE_EMPTY, TILE_SPAWN, TILE_EMPTY, TILE_SPAWN, TILE_EMPTY
};
int aFLOOR_4_4_TILES[15*4] = {
	TILE_SPAWN, TILE_UP, TILE_SPAWN, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, 				TILE_UP, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, 				TILE_EMPTY, TILE_UP, TILE_EMPTY,
	TILE_EMPTY, TILE_SPAWN, TILE_EMPTY, TILE_EMPTY, TILE_SPAWN, TILE_EMPTY, TILE_SPAWN, 			TILE_EMPTY, TILE_SPAWN, TILE_EMPTY, TILE_SPAWN, TILE_EMPTY, 			TILE_EMPTY, TILE_EMPTY, TILE_EMPTY,
	TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_INVALID, TILE_INVALID, TILE_INVALID, TILE_INVALID,		TILE_INVALID, TILE_INVALID, TILE_INVALID, TILE_INVALID, TILE_INVALID, 	TILE_EMPTY, TILE_EMPTY, TILE_EMPTY,
	TILE_EMPTY, TILE_UP, TILE_EMPTY, TILE_INVALID, TILE_INVALID, TILE_INVALID, TILE_INVALID,		TILE_INVALID, TILE_INVALID, TILE_INVALID, TILE_INVALID, TILE_INVALID, 	TILE_EMPTY, TILE_DOWN, TILE_EMPTY
};
int aFLOOR_4_5_TILES[3*3] = {
	TILE_EMPTY, TILE_DOWN, TILE_EMPTY,
	TILE_EMPTY, TILE_EMPTY, TILE_EMPTY,
	TILE_SPAWN, TILE_SPAWN, TILE_SPAWN
};
int aFLOOR_4_6_TILES[3*7] = {
	TILE_INVALID, TILE_UP, TILE_INVALID,
	TILE_SPAWN, TILE_SPAWN, TILE_SPAWN,
	TILE_EMPTY, TILE_EMPTY, TILE_EMPTY,
	TILE_EMPTY, TILE_EMPTY, TILE_UP,
	TILE_EMPTY, TILE_EMPTY, TILE_EMPTY,
	TILE_SPAWN, TILE_SPAWN, TILE_SPAWN,
	TILE_INVALID, TILE_DOWN, TILE_INVALID
};
int aFLOOR_4_7_TILES[3*7] = {
	TILE_INVALID, TILE_UP, TILE_INVALID,
	TILE_SPAWN, TILE_SPAWN, TILE_SPAWN,
	TILE_SPAWN, TILE_SPAWN, TILE_SPAWN,
	TILE_UP, TILE_EMPTY, TILE_UP,
	TILE_SPAWN, TILE_SPAWN, TILE_SPAWN,
	TILE_SPAWN, TILE_SPAWN, TILE_SPAWN,
	TILE_INVALID, TILE_DOWN, TILE_INVALID
};
int aFLOOR_4_8_TILES[3*7] = {
	TILE_INVALID, TILE_UP, TILE_INVALID,
	TILE_SPAWN, TILE_SPAWN, TILE_SPAWN,
	TILE_EMPTY, TILE_EMPTY, TILE_EMPTY,
	TILE_UP, TILE_EMPTY, TILE_EMPTY,
	TILE_EMPTY, TILE_EMPTY, TILE_EMPTY,
	TILE_SPAWN, TILE_SPAWN, TILE_SPAWN,
	TILE_INVALID, TILE_DOWN, TILE_INVALID
};
int aFLOOR_4_9_TILES[15*4] = {
	TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_SPAWN, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_UP, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_SPAWN, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY,
	TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_SPAWN, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_SPAWN, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY,
	TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_SPAWN, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_SPAWN, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY,
	TILE_EMPTY, TILE_DOWN, TILE_EMPTY, TILE_SPAWN, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_DOWN, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_SPAWN, TILE_EMPTY, TILE_DOWN, TILE_EMPTY
};
int aFLOOR_4_10_TILES[13*13] = {
	TILE_SPAWN, TILE_EMPTY, TILE_EMPTY, TILE_SPAWN, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, 			TILE_INVALID, TILE_INVALID, TILE_INVALID, TILE_INVALID, TILE_INVALID,
	TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_SPAWN, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, 			TILE_INVALID, TILE_INVALID, TILE_INVALID, TILE_INVALID, TILE_INVALID,
	TILE_SPAWN, TILE_EMPTY, TILE_INVALID, TILE_INVALID, TILE_INVALID, TILE_INVALID, TILE_INVALID, TILE_INVALID,	TILE_INVALID, TILE_INVALID, TILE_INVALID, TILE_INVALID, TILE_INVALID,
	TILE_EMPTY, TILE_EMPTY, TILE_INVALID, TILE_INVALID, TILE_INVALID, TILE_INVALID, TILE_INVALID, TILE_INVALID,	TILE_INVALID, TILE_INVALID, TILE_INVALID, TILE_INVALID, TILE_INVALID,
	TILE_SPAWN, TILE_EMPTY, TILE_INVALID, TILE_INVALID, TILE_INVALID, TILE_INVALID, TILE_INVALID, TILE_INVALID,	TILE_INVALID, TILE_INVALID, TILE_INVALID, TILE_INVALID, TILE_INVALID,
	TILE_EMPTY, TILE_EMPTY, TILE_INVALID, TILE_INVALID, TILE_INVALID, TILE_INVALID, TILE_INVALID, TILE_INVALID,	TILE_INVALID, TILE_INVALID, TILE_INVALID, TILE_INVALID, TILE_INVALID,
	TILE_SPAWN, TILE_EMPTY, TILE_INVALID, TILE_INVALID, TILE_INVALID, TILE_INVALID, TILE_INVALID, TILE_INVALID,	TILE_INVALID, TILE_INVALID, TILE_INVALID, TILE_INVALID, TILE_INVALID,
	TILE_EMPTY, TILE_EMPTY, TILE_INVALID, TILE_INVALID, TILE_INVALID, TILE_INVALID, TILE_INVALID, TILE_INVALID,	TILE_INVALID, TILE_INVALID, TILE_INVALID, TILE_INVALID, TILE_INVALID,

	TILE_SPAWN, TILE_EMPTY, TILE_INVALID, TILE_INVALID, TILE_INVALID, TILE_INVALID, TILE_INVALID, TILE_INVALID,	TILE_INVALID, TILE_INVALID, TILE_INVALID, TILE_EMPTY, TILE_SPAWN,
	TILE_UP, TILE_EMPTY, TILE_INVALID, TILE_INVALID, TILE_INVALID, TILE_INVALID, TILE_INVALID, TILE_INVALID,	TILE_INVALID, TILE_INVALID, TILE_INVALID, TILE_EMPTY, TILE_UP,
	TILE_SPAWN, TILE_EMPTY, TILE_INVALID, TILE_INVALID, TILE_INVALID, TILE_INVALID, TILE_INVALID, TILE_INVALID,	TILE_INVALID, TILE_INVALID, TILE_INVALID, TILE_EMPTY, TILE_SPAWN,
	TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY,				TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY,
	TILE_SPAWN, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_SPAWN, TILE_DOWN, TILE_SPAWN,				TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_SPAWN
};
int aFLOOR_4_11_TILES[3*3] = {
	TILE_EMPTY, TILE_EMPTY, TILE_EMPTY,
	TILE_DOWN, TILE_EMPTY, TILE_SPAWN,
	TILE_EMPTY, TILE_EMPTY, TILE_EMPTY
};
int aFLOOR_4_12_TILES[3*3] = {
	TILE_EMPTY, TILE_EMPTY, TILE_EMPTY,
	TILE_SPAWN, TILE_EMPTY, TILE_DOWN,
	TILE_EMPTY, TILE_EMPTY, TILE_EMPTY
};
int aFLOOR_4_13_TILES[5*7] = {
	TILE_INVALID, TILE_EMPTY, TILE_DOWN, TILE_EMPTY, TILE_INVALID,
	TILE_SPAWN, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_SPAWN,
	TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY,
	TILE_SPAWN, TILE_EMPTY, TILE_BOSS, TILE_EMPTY, TILE_SPAWN,
	TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY,
	TILE_SPAWN, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_SPAWN,
	TILE_INVALID, TILE_EMPTY, TILE_LOCKED_FAST_TRAVEL, TILE_EMPTY, TILE_INVALID
};



int aFLOOR_5_0_TILES[3*9] = {
	TILE_EMPTY, TILE_UP, TILE_EMPTY,
	TILE_EMPTY, TILE_EMPTY, TILE_EMPTY,
	TILE_EMPTY, TILE_BOSS, TILE_EMPTY,
	TILE_EMPTY, TILE_EMPTY, TILE_EMPTY,
	TILE_EMPTY, TILE_SPAWN, TILE_EMPTY,
	TILE_EMPTY, TILE_EMPTY, TILE_EMPTY,
	TILE_EMPTY, TILE_EMPTY, TILE_EMPTY,
	TILE_EMPTY, TILE_EMPTY, TILE_EMPTY,
	TILE_EMPTY, TILE_FAST_TRAVEL, TILE_EMPTY	
};
int aFLOOR_5_1_TILES[7*7] = {
	TILE_INVALID, TILE_EMPTY, TILE_EMPTY, TILE_UP, TILE_EMPTY, TILE_EMPTY, TILE_INVALID,
	TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY,
	TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY,
	TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_BOSS, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY,
	TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY,
	TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY, TILE_EMPTY,
	TILE_INVALID, TILE_EMPTY, TILE_EMPTY, TILE_DOWN, TILE_EMPTY, TILE_EMPTY, TILE_INVALID
};
int aFLOOR_5_2_TILES[3*9] = {
	TILE_EMPTY, TILE_CREDITS, TILE_EMPTY,
	TILE_SPAWN, TILE_EMPTY, TILE_SPAWN,
	TILE_EMPTY, TILE_EMPTY, TILE_EMPTY,
	TILE_SPAWN, TILE_EMPTY, TILE_SPAWN,
	TILE_EMPTY, TILE_EMPTY, TILE_EMPTY,
	TILE_SPAWN, TILE_EMPTY, TILE_SPAWN,
	TILE_EMPTY, TILE_EMPTY, TILE_EMPTY,
	TILE_SPAWN, TILE_EMPTY, TILE_SPAWN,
	TILE_EMPTY, TILE_DOWN, TILE_EMPTY
};



//Packed all the floors into areas
int* aAREA_0_TILES[3] = {
	aFLOOR_0_0_TILES,
	aFLOOR_0_1_TILES,
	aFLOOR_0_2_TILES
};
int* aAREA_1_TILES[5] = {
	aFLOOR_1_0_TILES,
	aFLOOR_1_1_TILES,
	aFLOOR_1_2_TILES,
	aFLOOR_1_3_TILES,
	aFLOOR_1_4_TILES
};
int* aAREA_2_TILES[7] = {
	aFLOOR_2_0_TILES,
	aFLOOR_2_1_TILES,
	aFLOOR_2_2_TILES,
	aFLOOR_2_3_TILES,
	aFLOOR_2_4_TILES,
	aFLOOR_2_5_TILES,
	aFLOOR_2_6_TILES
};
int* aAREA_3_TILES[7] = {
	aFLOOR_3_0_TILES,
	aFLOOR_3_1_TILES,
	aFLOOR_3_2_TILES,
	aFLOOR_3_3_TILES,
	aFLOOR_3_4_TILES,
	aFLOOR_3_5_TILES,
	aFLOOR_3_6_TILES
};
int* aAREA_4_TILES[14] = {
	aFLOOR_4_0_TILES,
	aFLOOR_4_1_TILES,
	aFLOOR_4_2_TILES,
	aFLOOR_4_3_TILES,
	aFLOOR_4_4_TILES,
	aFLOOR_4_5_TILES,
	aFLOOR_4_6_TILES,
	aFLOOR_4_7_TILES,
	aFLOOR_4_8_TILES,
	aFLOOR_4_9_TILES,
	aFLOOR_4_10_TILES,
	aFLOOR_4_11_TILES,
	aFLOOR_4_12_TILES,
	aFLOOR_4_13_TILES
};
int* aAREA_5_TILES[3] = {
	aFLOOR_5_0_TILES,
	aFLOOR_5_1_TILES,
	aFLOOR_5_2_TILES
};


//Packed all areas into into an array
int** aALL_AREA_TILES[TOTAL_AREAS] = {
	aAREA_0_TILES,
	aAREA_1_TILES,
	aAREA_2_TILES,
	aAREA_3_TILES,
	aAREA_4_TILES,
	aAREA_5_TILES
};

#endif